on:
  push:
    tags: ["*"]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      # Etapa condicional para limpar node_modules e package-lock.json no Windows
      - name: Clean node_modules and package-lock on Windows
        if: matrix.os == 'windows-latest'
        run: |
          Remove-Item -Recurse -Force node_modules, package-lock.json
        shell: pwsh

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Electron App
        run: npm run build

      - name: Package and Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: true
