on:
  push:
    tags: ["*"]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: apt-update
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get update

      - name: autoremove
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt autoremove

      - name: Install libarchive rpm on Linux
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get install libarchive-tools rpm

      - name: Install macOS dependencies
        if: startsWith(matrix.os, 'macos-latest')
        run: |
          # Ignorar erro se os Xcode Command Line Tools já estiverem instalados
          xcode-select --install || true
          # Garantir que o brew está atualizado
          brew update || true
          # Instalar pacotes necessários no macOS
          brew install libtool automake cmake pkg-config || true

      - name: Clean npm cache and remove node_modules (if on macOS)
        if: startsWith(matrix.os, 'macos-latest')
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: true
